/* soapAuthenticationBehaviorBindingProxy.h
   Generated by gSOAP 2.8.45 for onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapAuthenticationBehaviorBindingProxy_H
#define soapAuthenticationBehaviorBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC AuthenticationBehaviorBindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        bool soap_own; ///< flag indicating that this context is owned by this proxy when context is shared
        /// Endpoint URL of service 'AuthenticationBehaviorBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in onvif.h, if any
        /// Construct a proxy with new managing context
        AuthenticationBehaviorBindingProxy();
        /// Copy constructor
        AuthenticationBehaviorBindingProxy(const AuthenticationBehaviorBindingProxy& rhs);
        /// Construct proxy given a shared managing context
        AuthenticationBehaviorBindingProxy(struct soap*);
        /// Constructor taking an endpoint URL
        AuthenticationBehaviorBindingProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        AuthenticationBehaviorBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        AuthenticationBehaviorBindingProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        AuthenticationBehaviorBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes non-shared managing context only (use destroy() to delete deserialized data)
        virtual ~AuthenticationBehaviorBindingProxy();
        /// Initializer used by constructors
        virtual void AuthenticationBehaviorBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual AuthenticationBehaviorBindingProxy *copy() SOAP_PURE_VIRTUAL;
        /// Copy assignment
        AuthenticationBehaviorBindingProxy& operator=(const AuthenticationBehaviorBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Add SOAP Header to message
        virtual void soap_header(char *wsa__MessageID, struct wsa__Relationship *wsa__RelatesTo, struct wsa__EndpointReferenceType *wsa__From, struct wsa__EndpointReferenceType *wsa__ReplyTo, struct wsa__EndpointReferenceType *wsa__FaultTo, char *wsa__To, char *wsa__Action, struct wsdd__AppSequenceType *wsdd__AppSequence, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct _wsse__Security *wsse__Security);
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault string (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail as string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'GetServiceCapabilities' (returns SOAP_OK or error code)
        virtual int GetServiceCapabilities(_ns4__GetServiceCapabilities *ns4__GetServiceCapabilities, _ns4__GetServiceCapabilitiesResponse &ns4__GetServiceCapabilitiesResponse)
        { return this->GetServiceCapabilities(NULL, NULL, ns4__GetServiceCapabilities, ns4__GetServiceCapabilitiesResponse); }
        virtual int GetServiceCapabilities(const char *soap_endpoint, const char *soap_action, _ns4__GetServiceCapabilities *ns4__GetServiceCapabilities, _ns4__GetServiceCapabilitiesResponse &ns4__GetServiceCapabilitiesResponse);
        /// Web service operation 'GetAuthenticationProfileInfo' (returns SOAP_OK or error code)
        virtual int GetAuthenticationProfileInfo(_ns4__GetAuthenticationProfileInfo *ns4__GetAuthenticationProfileInfo, _ns4__GetAuthenticationProfileInfoResponse &ns4__GetAuthenticationProfileInfoResponse)
        { return this->GetAuthenticationProfileInfo(NULL, NULL, ns4__GetAuthenticationProfileInfo, ns4__GetAuthenticationProfileInfoResponse); }
        virtual int GetAuthenticationProfileInfo(const char *soap_endpoint, const char *soap_action, _ns4__GetAuthenticationProfileInfo *ns4__GetAuthenticationProfileInfo, _ns4__GetAuthenticationProfileInfoResponse &ns4__GetAuthenticationProfileInfoResponse);
        /// Web service operation 'GetAuthenticationProfileInfoList' (returns SOAP_OK or error code)
        virtual int GetAuthenticationProfileInfoList(_ns4__GetAuthenticationProfileInfoList *ns4__GetAuthenticationProfileInfoList, _ns4__GetAuthenticationProfileInfoListResponse &ns4__GetAuthenticationProfileInfoListResponse)
        { return this->GetAuthenticationProfileInfoList(NULL, NULL, ns4__GetAuthenticationProfileInfoList, ns4__GetAuthenticationProfileInfoListResponse); }
        virtual int GetAuthenticationProfileInfoList(const char *soap_endpoint, const char *soap_action, _ns4__GetAuthenticationProfileInfoList *ns4__GetAuthenticationProfileInfoList, _ns4__GetAuthenticationProfileInfoListResponse &ns4__GetAuthenticationProfileInfoListResponse);
        /// Web service operation 'GetAuthenticationProfiles' (returns SOAP_OK or error code)
        virtual int GetAuthenticationProfiles(_ns4__GetAuthenticationProfiles *ns4__GetAuthenticationProfiles, _ns4__GetAuthenticationProfilesResponse &ns4__GetAuthenticationProfilesResponse)
        { return this->GetAuthenticationProfiles(NULL, NULL, ns4__GetAuthenticationProfiles, ns4__GetAuthenticationProfilesResponse); }
        virtual int GetAuthenticationProfiles(const char *soap_endpoint, const char *soap_action, _ns4__GetAuthenticationProfiles *ns4__GetAuthenticationProfiles, _ns4__GetAuthenticationProfilesResponse &ns4__GetAuthenticationProfilesResponse);
        /// Web service operation 'GetAuthenticationProfileList' (returns SOAP_OK or error code)
        virtual int GetAuthenticationProfileList(_ns4__GetAuthenticationProfileList *ns4__GetAuthenticationProfileList, _ns4__GetAuthenticationProfileListResponse &ns4__GetAuthenticationProfileListResponse)
        { return this->GetAuthenticationProfileList(NULL, NULL, ns4__GetAuthenticationProfileList, ns4__GetAuthenticationProfileListResponse); }
        virtual int GetAuthenticationProfileList(const char *soap_endpoint, const char *soap_action, _ns4__GetAuthenticationProfileList *ns4__GetAuthenticationProfileList, _ns4__GetAuthenticationProfileListResponse &ns4__GetAuthenticationProfileListResponse);
        /// Web service operation 'CreateAuthenticationProfile' (returns SOAP_OK or error code)
        virtual int CreateAuthenticationProfile(_ns4__CreateAuthenticationProfile *ns4__CreateAuthenticationProfile, _ns4__CreateAuthenticationProfileResponse &ns4__CreateAuthenticationProfileResponse)
        { return this->CreateAuthenticationProfile(NULL, NULL, ns4__CreateAuthenticationProfile, ns4__CreateAuthenticationProfileResponse); }
        virtual int CreateAuthenticationProfile(const char *soap_endpoint, const char *soap_action, _ns4__CreateAuthenticationProfile *ns4__CreateAuthenticationProfile, _ns4__CreateAuthenticationProfileResponse &ns4__CreateAuthenticationProfileResponse);
        /// Web service operation 'SetAuthenticationProfile' (returns SOAP_OK or error code)
        virtual int SetAuthenticationProfile(_ns4__SetAuthenticationProfile *ns4__SetAuthenticationProfile, _ns4__SetAuthenticationProfileResponse &ns4__SetAuthenticationProfileResponse)
        { return this->SetAuthenticationProfile(NULL, NULL, ns4__SetAuthenticationProfile, ns4__SetAuthenticationProfileResponse); }
        virtual int SetAuthenticationProfile(const char *soap_endpoint, const char *soap_action, _ns4__SetAuthenticationProfile *ns4__SetAuthenticationProfile, _ns4__SetAuthenticationProfileResponse &ns4__SetAuthenticationProfileResponse);
        /// Web service operation 'ModifyAuthenticationProfile' (returns SOAP_OK or error code)
        virtual int ModifyAuthenticationProfile(_ns4__ModifyAuthenticationProfile *ns4__ModifyAuthenticationProfile, _ns4__ModifyAuthenticationProfileResponse &ns4__ModifyAuthenticationProfileResponse)
        { return this->ModifyAuthenticationProfile(NULL, NULL, ns4__ModifyAuthenticationProfile, ns4__ModifyAuthenticationProfileResponse); }
        virtual int ModifyAuthenticationProfile(const char *soap_endpoint, const char *soap_action, _ns4__ModifyAuthenticationProfile *ns4__ModifyAuthenticationProfile, _ns4__ModifyAuthenticationProfileResponse &ns4__ModifyAuthenticationProfileResponse);
        /// Web service operation 'DeleteAuthenticationProfile' (returns SOAP_OK or error code)
        virtual int DeleteAuthenticationProfile(_ns4__DeleteAuthenticationProfile *ns4__DeleteAuthenticationProfile, _ns4__DeleteAuthenticationProfileResponse &ns4__DeleteAuthenticationProfileResponse)
        { return this->DeleteAuthenticationProfile(NULL, NULL, ns4__DeleteAuthenticationProfile, ns4__DeleteAuthenticationProfileResponse); }
        virtual int DeleteAuthenticationProfile(const char *soap_endpoint, const char *soap_action, _ns4__DeleteAuthenticationProfile *ns4__DeleteAuthenticationProfile, _ns4__DeleteAuthenticationProfileResponse &ns4__DeleteAuthenticationProfileResponse);
        /// Web service operation 'GetSecurityLevelInfo' (returns SOAP_OK or error code)
        virtual int GetSecurityLevelInfo(_ns4__GetSecurityLevelInfo *ns4__GetSecurityLevelInfo, _ns4__GetSecurityLevelInfoResponse &ns4__GetSecurityLevelInfoResponse)
        { return this->GetSecurityLevelInfo(NULL, NULL, ns4__GetSecurityLevelInfo, ns4__GetSecurityLevelInfoResponse); }
        virtual int GetSecurityLevelInfo(const char *soap_endpoint, const char *soap_action, _ns4__GetSecurityLevelInfo *ns4__GetSecurityLevelInfo, _ns4__GetSecurityLevelInfoResponse &ns4__GetSecurityLevelInfoResponse);
        /// Web service operation 'GetSecurityLevelInfoList' (returns SOAP_OK or error code)
        virtual int GetSecurityLevelInfoList(_ns4__GetSecurityLevelInfoList *ns4__GetSecurityLevelInfoList, _ns4__GetSecurityLevelInfoListResponse &ns4__GetSecurityLevelInfoListResponse)
        { return this->GetSecurityLevelInfoList(NULL, NULL, ns4__GetSecurityLevelInfoList, ns4__GetSecurityLevelInfoListResponse); }
        virtual int GetSecurityLevelInfoList(const char *soap_endpoint, const char *soap_action, _ns4__GetSecurityLevelInfoList *ns4__GetSecurityLevelInfoList, _ns4__GetSecurityLevelInfoListResponse &ns4__GetSecurityLevelInfoListResponse);
        /// Web service operation 'GetSecurityLevels' (returns SOAP_OK or error code)
        virtual int GetSecurityLevels(_ns4__GetSecurityLevels *ns4__GetSecurityLevels, _ns4__GetSecurityLevelsResponse &ns4__GetSecurityLevelsResponse)
        { return this->GetSecurityLevels(NULL, NULL, ns4__GetSecurityLevels, ns4__GetSecurityLevelsResponse); }
        virtual int GetSecurityLevels(const char *soap_endpoint, const char *soap_action, _ns4__GetSecurityLevels *ns4__GetSecurityLevels, _ns4__GetSecurityLevelsResponse &ns4__GetSecurityLevelsResponse);
        /// Web service operation 'GetSecurityLevelList' (returns SOAP_OK or error code)
        virtual int GetSecurityLevelList(_ns4__GetSecurityLevelList *ns4__GetSecurityLevelList, _ns4__GetSecurityLevelListResponse &ns4__GetSecurityLevelListResponse)
        { return this->GetSecurityLevelList(NULL, NULL, ns4__GetSecurityLevelList, ns4__GetSecurityLevelListResponse); }
        virtual int GetSecurityLevelList(const char *soap_endpoint, const char *soap_action, _ns4__GetSecurityLevelList *ns4__GetSecurityLevelList, _ns4__GetSecurityLevelListResponse &ns4__GetSecurityLevelListResponse);
        /// Web service operation 'CreateSecurityLevel' (returns SOAP_OK or error code)
        virtual int CreateSecurityLevel(_ns4__CreateSecurityLevel *ns4__CreateSecurityLevel, _ns4__CreateSecurityLevelResponse &ns4__CreateSecurityLevelResponse)
        { return this->CreateSecurityLevel(NULL, NULL, ns4__CreateSecurityLevel, ns4__CreateSecurityLevelResponse); }
        virtual int CreateSecurityLevel(const char *soap_endpoint, const char *soap_action, _ns4__CreateSecurityLevel *ns4__CreateSecurityLevel, _ns4__CreateSecurityLevelResponse &ns4__CreateSecurityLevelResponse);
        /// Web service operation 'SetSecurityLevel' (returns SOAP_OK or error code)
        virtual int SetSecurityLevel(_ns4__SetSecurityLevel *ns4__SetSecurityLevel, _ns4__SetSecurityLevelResponse &ns4__SetSecurityLevelResponse)
        { return this->SetSecurityLevel(NULL, NULL, ns4__SetSecurityLevel, ns4__SetSecurityLevelResponse); }
        virtual int SetSecurityLevel(const char *soap_endpoint, const char *soap_action, _ns4__SetSecurityLevel *ns4__SetSecurityLevel, _ns4__SetSecurityLevelResponse &ns4__SetSecurityLevelResponse);
        /// Web service operation 'ModifySecurityLevel' (returns SOAP_OK or error code)
        virtual int ModifySecurityLevel(_ns4__ModifySecurityLevel *ns4__ModifySecurityLevel, _ns4__ModifySecurityLevelResponse &ns4__ModifySecurityLevelResponse)
        { return this->ModifySecurityLevel(NULL, NULL, ns4__ModifySecurityLevel, ns4__ModifySecurityLevelResponse); }
        virtual int ModifySecurityLevel(const char *soap_endpoint, const char *soap_action, _ns4__ModifySecurityLevel *ns4__ModifySecurityLevel, _ns4__ModifySecurityLevelResponse &ns4__ModifySecurityLevelResponse);
        /// Web service operation 'DeleteSecurityLevel' (returns SOAP_OK or error code)
        virtual int DeleteSecurityLevel(_ns4__DeleteSecurityLevel *ns4__DeleteSecurityLevel, _ns4__DeleteSecurityLevelResponse &ns4__DeleteSecurityLevelResponse)
        { return this->DeleteSecurityLevel(NULL, NULL, ns4__DeleteSecurityLevel, ns4__DeleteSecurityLevelResponse); }
        virtual int DeleteSecurityLevel(const char *soap_endpoint, const char *soap_action, _ns4__DeleteSecurityLevel *ns4__DeleteSecurityLevel, _ns4__DeleteSecurityLevelResponse &ns4__DeleteSecurityLevelResponse);
    };
#endif
