/* soapAuthenticationBehaviorBindingProxy.cpp
   Generated by gSOAP 2.8.45 for onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "soapAuthenticationBehaviorBindingProxy.h"

AuthenticationBehaviorBindingProxy::AuthenticationBehaviorBindingProxy()
{	this->soap = soap_new();
	this->soap_own = true;
	AuthenticationBehaviorBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

AuthenticationBehaviorBindingProxy::AuthenticationBehaviorBindingProxy(const AuthenticationBehaviorBindingProxy& rhs)
{	this->soap = rhs.soap;
	this->soap_own = false;
	this->soap_endpoint = rhs.soap_endpoint;
}

AuthenticationBehaviorBindingProxy::AuthenticationBehaviorBindingProxy(struct soap *_soap)
{	this->soap = _soap;
	this->soap_own = false;
	AuthenticationBehaviorBindingProxy_init(_soap->imode, _soap->omode);
}

AuthenticationBehaviorBindingProxy::AuthenticationBehaviorBindingProxy(const char *endpoint)
{	this->soap = soap_new();
	this->soap_own = true;
	AuthenticationBehaviorBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = endpoint;
}

AuthenticationBehaviorBindingProxy::AuthenticationBehaviorBindingProxy(soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	AuthenticationBehaviorBindingProxy_init(iomode, iomode);
}

AuthenticationBehaviorBindingProxy::AuthenticationBehaviorBindingProxy(const char *endpoint, soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	AuthenticationBehaviorBindingProxy_init(iomode, iomode);
	soap_endpoint = endpoint;
}

AuthenticationBehaviorBindingProxy::AuthenticationBehaviorBindingProxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->soap_own = true;
	AuthenticationBehaviorBindingProxy_init(imode, omode);
}

AuthenticationBehaviorBindingProxy::~AuthenticationBehaviorBindingProxy()
{	if (this->soap_own)
		soap_free(this->soap);
}

void AuthenticationBehaviorBindingProxy::AuthenticationBehaviorBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] = {
        {"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
        {"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
        {"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
        {"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
        {"wsa", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL, NULL},
        {"wsdd", "http://schemas.xmlsoap.org/ws/2005/04/discovery", NULL, NULL},
        {"chan", "http://schemas.microsoft.com/ws/2005/02/duplex", NULL, NULL},
        {"wsa5", "http://www.w3.org/2005/08/addressing", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL},
        {"c14n", "http://www.w3.org/2001/10/xml-exc-c14n#", NULL, NULL},
        {"ds", "http://www.w3.org/2000/09/xmldsig#", NULL, NULL},
        {"saml1", "urn:oasis:names:tc:SAML:1.0:assertion", NULL, NULL},
        {"saml2", "urn:oasis:names:tc:SAML:2.0:assertion", NULL, NULL},
        {"wsu", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", NULL, NULL},
        {"xenc", "http://www.w3.org/2001/04/xmlenc#", NULL, NULL},
        {"wsc", "http://docs.oasis-open.org/ws-sx/ws-secureconversation/200512", NULL, NULL},
        {"wsse", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", "http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd", NULL},
        {"ns1", "http://www.onvif.org/ver20/analytics/humanface", NULL, NULL},
        {"ns2", "http://www.onvif.org/ver20/analytics/humanbody", NULL, NULL},
        {"ns5", "http://www.onvif.org/ver10/pacs", NULL, NULL},
        {"xmime", "http://tempuri.org/xmime.xsd", NULL, NULL},
        {"xop", "http://www.w3.org/2004/08/xop/include", NULL, NULL},
        {"tt", "http://www.onvif.org/ver10/schema", NULL, NULL},
        {"wsrfbf", "http://docs.oasis-open.org/wsrf/bf-2", NULL, NULL},
        {"wstop", "http://docs.oasis-open.org/wsn/t-1", NULL, NULL},
        {"wsrfr", "http://docs.oasis-open.org/wsrf/r-2", NULL, NULL},
        {"ns10", "http://www.onvif.org/ver10/schedule/wsdl", NULL, NULL},
        {"ns11", "http://www.onvif.org/ver10/thermal/wsdl", NULL, NULL},
        {"ns12", "http://www.onvif.org/ver10/uplink/wsdl", NULL, NULL},
        {"ns13", "http://www.onvif.org/ver10/accesscontrol/wsdl", NULL, NULL},
        {"ns14", "http://www.onvif.org/ver10/accessrules/wsdl", NULL, NULL},
        {"ns3", "http://www.onvif.org/ver10/actionengine/wsdl", NULL, NULL},
        {"ns4", "http://www.onvif.org/ver10/authenticationbehavior/wsdl", NULL, NULL},
        {"ns6", "http://www.onvif.org/ver10/credential/wsdl", NULL, NULL},
        {"ns7", "http://www.onvif.org/ver10/doorcontrol/wsdl", NULL, NULL},
        {"ns8", "http://www.onvif.org/ver20/media/wsdl", NULL, NULL},
        {"ns9", "http://www.onvif.org/ver10/provisioning/wsdl", NULL, NULL},
        {"tan", "http://www.onvif.org/ver20/analytics/wsdl", NULL, NULL},
        {"tas", "http://www.onvif.org/ver10/advancedsecurity/wsdl", NULL, NULL},
        {"tdn", "http://www.onvif.org/ver10/network/wsdl", NULL, NULL},
        {"tds", "http://www.onvif.org/ver10/device/wsdl", NULL, NULL},
        {"tev", "http://www.onvif.org/ver10/events/wsdl", NULL, NULL},
        {"wsnt", "http://docs.oasis-open.org/wsn/b-2", NULL, NULL},
        {"timg", "http://www.onvif.org/ver20/imaging/wsdl", NULL, NULL},
        {"tls", "http://www.onvif.org/ver10/display/wsdl", NULL, NULL},
        {"tmd", "http://www.onvif.org/ver10/deviceIO/wsdl", NULL, NULL},
        {"tptz", "http://www.onvif.org/ver20/ptz/wsdl", NULL, NULL},
        {"trc", "http://www.onvif.org/ver10/recording/wsdl", NULL, NULL},
        {"trp", "http://www.onvif.org/ver10/replay/wsdl", NULL, NULL},
        {"trt", "http://www.onvif.org/ver10/media/wsdl", NULL, NULL},
        {"trv", "http://www.onvif.org/ver10/receiver/wsdl", NULL, NULL},
        {"tse", "http://www.onvif.org/ver10/search/wsdl", NULL, NULL},
        {NULL, NULL, NULL, NULL}
    };
	soap_set_namespaces(this->soap, namespaces);
}

#ifndef WITH_PURE_VIRTUAL
AuthenticationBehaviorBindingProxy *AuthenticationBehaviorBindingProxy::copy()
{	AuthenticationBehaviorBindingProxy *dup = SOAP_NEW_COPY(AuthenticationBehaviorBindingProxy);
	if (dup)
		soap_copy_context(dup->soap, this->soap);
	return dup;
}
#endif

AuthenticationBehaviorBindingProxy& AuthenticationBehaviorBindingProxy::operator=(const AuthenticationBehaviorBindingProxy& rhs)
{	if (this->soap_own)
		soap_free(this->soap);
	this->soap = rhs.soap;
	this->soap_own = false;
	this->soap_endpoint = rhs.soap_endpoint;
	return *this;
}

void AuthenticationBehaviorBindingProxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void AuthenticationBehaviorBindingProxy::reset()
{	this->destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	AuthenticationBehaviorBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void AuthenticationBehaviorBindingProxy::soap_noheader()
{	this->soap->header = NULL;
}

void AuthenticationBehaviorBindingProxy::soap_header(char *wsa__MessageID, struct wsa__Relationship *wsa__RelatesTo, struct wsa__EndpointReferenceType *wsa__From, struct wsa__EndpointReferenceType *wsa__ReplyTo, struct wsa__EndpointReferenceType *wsa__FaultTo, char *wsa__To, char *wsa__Action, struct wsdd__AppSequenceType *wsdd__AppSequence, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct _wsse__Security *wsse__Security)
{	::soap_header(this->soap);
	this->soap->header->wsa__MessageID = wsa__MessageID;
	this->soap->header->wsa__RelatesTo = wsa__RelatesTo;
	this->soap->header->wsa__From = wsa__From;
	this->soap->header->wsa__ReplyTo = wsa__ReplyTo;
	this->soap->header->wsa__FaultTo = wsa__FaultTo;
	this->soap->header->wsa__To = wsa__To;
	this->soap->header->wsa__Action = wsa__Action;
	this->soap->header->wsdd__AppSequence = wsdd__AppSequence;
	this->soap->header->wsa5__MessageID = wsa5__MessageID;
	this->soap->header->wsa5__RelatesTo = wsa5__RelatesTo;
	this->soap->header->wsa5__From = wsa5__From;
	this->soap->header->wsa5__ReplyTo = wsa5__ReplyTo;
	this->soap->header->wsa5__FaultTo = wsa5__FaultTo;
	this->soap->header->wsa5__To = wsa5__To;
	this->soap->header->wsa5__Action = wsa5__Action;
	this->soap->header->chan__ChannelInstance = chan__ChannelInstance;
	this->soap->header->wsse__Security = wsse__Security;
}

::SOAP_ENV__Header *AuthenticationBehaviorBindingProxy::soap_header()
{	return this->soap->header;
}

::SOAP_ENV__Fault *AuthenticationBehaviorBindingProxy::soap_fault()
{	return this->soap->fault;
}

const char *AuthenticationBehaviorBindingProxy::soap_fault_string()
{	return *soap_faultstring(this->soap);
}

const char *AuthenticationBehaviorBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this->soap);
}

int AuthenticationBehaviorBindingProxy::soap_close_socket()
{	return soap_closesock(this->soap);
}

int AuthenticationBehaviorBindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

void AuthenticationBehaviorBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void AuthenticationBehaviorBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *AuthenticationBehaviorBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int AuthenticationBehaviorBindingProxy::GetServiceCapabilities(const char *endpoint, const char *soap_action, _ns4__GetServiceCapabilities *ns4__GetServiceCapabilities, _ns4__GetServiceCapabilitiesResponse &ns4__GetServiceCapabilitiesResponse)
{	struct soap *soap = this->soap;
	struct __ns4__GetServiceCapabilities soap_tmp___ns4__GetServiceCapabilities;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetServiceCapabilities";
	soap_tmp___ns4__GetServiceCapabilities.ns4__GetServiceCapabilities = ns4__GetServiceCapabilities;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns4__GetServiceCapabilities(soap, &soap_tmp___ns4__GetServiceCapabilities);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns4__GetServiceCapabilities(soap, &soap_tmp___ns4__GetServiceCapabilities, "-ns4:GetServiceCapabilities", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns4__GetServiceCapabilities(soap, &soap_tmp___ns4__GetServiceCapabilities, "-ns4:GetServiceCapabilities", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns4__GetServiceCapabilitiesResponse*>(&ns4__GetServiceCapabilitiesResponse)) // NULL ref?
		return soap_closesock(soap);
	ns4__GetServiceCapabilitiesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns4__GetServiceCapabilitiesResponse.soap_get(soap, "ns4:GetServiceCapabilitiesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::GetAuthenticationProfileInfo(const char *endpoint, const char *soap_action, _ns4__GetAuthenticationProfileInfo *ns4__GetAuthenticationProfileInfo, _ns4__GetAuthenticationProfileInfoResponse &ns4__GetAuthenticationProfileInfoResponse)
{	struct soap *soap = this->soap;
	struct __ns4__GetAuthenticationProfileInfo soap_tmp___ns4__GetAuthenticationProfileInfo;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetAuthenticationProfileInfo";
	soap_tmp___ns4__GetAuthenticationProfileInfo.ns4__GetAuthenticationProfileInfo = ns4__GetAuthenticationProfileInfo;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns4__GetAuthenticationProfileInfo(soap, &soap_tmp___ns4__GetAuthenticationProfileInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns4__GetAuthenticationProfileInfo(soap, &soap_tmp___ns4__GetAuthenticationProfileInfo, "-ns4:GetAuthenticationProfileInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns4__GetAuthenticationProfileInfo(soap, &soap_tmp___ns4__GetAuthenticationProfileInfo, "-ns4:GetAuthenticationProfileInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns4__GetAuthenticationProfileInfoResponse*>(&ns4__GetAuthenticationProfileInfoResponse)) // NULL ref?
		return soap_closesock(soap);
	ns4__GetAuthenticationProfileInfoResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns4__GetAuthenticationProfileInfoResponse.soap_get(soap, "ns4:GetAuthenticationProfileInfoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::GetAuthenticationProfileInfoList(const char *endpoint, const char *soap_action, _ns4__GetAuthenticationProfileInfoList *ns4__GetAuthenticationProfileInfoList, _ns4__GetAuthenticationProfileInfoListResponse &ns4__GetAuthenticationProfileInfoListResponse)
{	struct soap *soap = this->soap;
	struct __ns4__GetAuthenticationProfileInfoList soap_tmp___ns4__GetAuthenticationProfileInfoList;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetAuthenticationProfileInfoList";
	soap_tmp___ns4__GetAuthenticationProfileInfoList.ns4__GetAuthenticationProfileInfoList = ns4__GetAuthenticationProfileInfoList;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns4__GetAuthenticationProfileInfoList(soap, &soap_tmp___ns4__GetAuthenticationProfileInfoList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns4__GetAuthenticationProfileInfoList(soap, &soap_tmp___ns4__GetAuthenticationProfileInfoList, "-ns4:GetAuthenticationProfileInfoList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns4__GetAuthenticationProfileInfoList(soap, &soap_tmp___ns4__GetAuthenticationProfileInfoList, "-ns4:GetAuthenticationProfileInfoList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns4__GetAuthenticationProfileInfoListResponse*>(&ns4__GetAuthenticationProfileInfoListResponse)) // NULL ref?
		return soap_closesock(soap);
	ns4__GetAuthenticationProfileInfoListResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns4__GetAuthenticationProfileInfoListResponse.soap_get(soap, "ns4:GetAuthenticationProfileInfoListResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::GetAuthenticationProfiles(const char *endpoint, const char *soap_action, _ns4__GetAuthenticationProfiles *ns4__GetAuthenticationProfiles, _ns4__GetAuthenticationProfilesResponse &ns4__GetAuthenticationProfilesResponse)
{	struct soap *soap = this->soap;
	struct __ns4__GetAuthenticationProfiles soap_tmp___ns4__GetAuthenticationProfiles;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetAuthenticationProfiles";
	soap_tmp___ns4__GetAuthenticationProfiles.ns4__GetAuthenticationProfiles = ns4__GetAuthenticationProfiles;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns4__GetAuthenticationProfiles(soap, &soap_tmp___ns4__GetAuthenticationProfiles);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns4__GetAuthenticationProfiles(soap, &soap_tmp___ns4__GetAuthenticationProfiles, "-ns4:GetAuthenticationProfiles", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns4__GetAuthenticationProfiles(soap, &soap_tmp___ns4__GetAuthenticationProfiles, "-ns4:GetAuthenticationProfiles", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns4__GetAuthenticationProfilesResponse*>(&ns4__GetAuthenticationProfilesResponse)) // NULL ref?
		return soap_closesock(soap);
	ns4__GetAuthenticationProfilesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns4__GetAuthenticationProfilesResponse.soap_get(soap, "ns4:GetAuthenticationProfilesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::GetAuthenticationProfileList(const char *endpoint, const char *soap_action, _ns4__GetAuthenticationProfileList *ns4__GetAuthenticationProfileList, _ns4__GetAuthenticationProfileListResponse &ns4__GetAuthenticationProfileListResponse)
{	struct soap *soap = this->soap;
	struct __ns4__GetAuthenticationProfileList soap_tmp___ns4__GetAuthenticationProfileList;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetAuthenticationProfileList";
	soap_tmp___ns4__GetAuthenticationProfileList.ns4__GetAuthenticationProfileList = ns4__GetAuthenticationProfileList;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns4__GetAuthenticationProfileList(soap, &soap_tmp___ns4__GetAuthenticationProfileList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns4__GetAuthenticationProfileList(soap, &soap_tmp___ns4__GetAuthenticationProfileList, "-ns4:GetAuthenticationProfileList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns4__GetAuthenticationProfileList(soap, &soap_tmp___ns4__GetAuthenticationProfileList, "-ns4:GetAuthenticationProfileList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns4__GetAuthenticationProfileListResponse*>(&ns4__GetAuthenticationProfileListResponse)) // NULL ref?
		return soap_closesock(soap);
	ns4__GetAuthenticationProfileListResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns4__GetAuthenticationProfileListResponse.soap_get(soap, "ns4:GetAuthenticationProfileListResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::CreateAuthenticationProfile(const char *endpoint, const char *soap_action, _ns4__CreateAuthenticationProfile *ns4__CreateAuthenticationProfile, _ns4__CreateAuthenticationProfileResponse &ns4__CreateAuthenticationProfileResponse)
{	struct soap *soap = this->soap;
	struct __ns4__CreateAuthenticationProfile soap_tmp___ns4__CreateAuthenticationProfile;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/CreateAuthenticationProfile";
	soap_tmp___ns4__CreateAuthenticationProfile.ns4__CreateAuthenticationProfile = ns4__CreateAuthenticationProfile;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns4__CreateAuthenticationProfile(soap, &soap_tmp___ns4__CreateAuthenticationProfile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns4__CreateAuthenticationProfile(soap, &soap_tmp___ns4__CreateAuthenticationProfile, "-ns4:CreateAuthenticationProfile", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns4__CreateAuthenticationProfile(soap, &soap_tmp___ns4__CreateAuthenticationProfile, "-ns4:CreateAuthenticationProfile", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns4__CreateAuthenticationProfileResponse*>(&ns4__CreateAuthenticationProfileResponse)) // NULL ref?
		return soap_closesock(soap);
	ns4__CreateAuthenticationProfileResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns4__CreateAuthenticationProfileResponse.soap_get(soap, "ns4:CreateAuthenticationProfileResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::SetAuthenticationProfile(const char *endpoint, const char *soap_action, _ns4__SetAuthenticationProfile *ns4__SetAuthenticationProfile, _ns4__SetAuthenticationProfileResponse &ns4__SetAuthenticationProfileResponse)
{	struct soap *soap = this->soap;
	struct __ns4__SetAuthenticationProfile soap_tmp___ns4__SetAuthenticationProfile;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/SetAuthenticationProfile";
	soap_tmp___ns4__SetAuthenticationProfile.ns4__SetAuthenticationProfile = ns4__SetAuthenticationProfile;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns4__SetAuthenticationProfile(soap, &soap_tmp___ns4__SetAuthenticationProfile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns4__SetAuthenticationProfile(soap, &soap_tmp___ns4__SetAuthenticationProfile, "-ns4:SetAuthenticationProfile", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns4__SetAuthenticationProfile(soap, &soap_tmp___ns4__SetAuthenticationProfile, "-ns4:SetAuthenticationProfile", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns4__SetAuthenticationProfileResponse*>(&ns4__SetAuthenticationProfileResponse)) // NULL ref?
		return soap_closesock(soap);
	ns4__SetAuthenticationProfileResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns4__SetAuthenticationProfileResponse.soap_get(soap, "ns4:SetAuthenticationProfileResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::ModifyAuthenticationProfile(const char *endpoint, const char *soap_action, _ns4__ModifyAuthenticationProfile *ns4__ModifyAuthenticationProfile, _ns4__ModifyAuthenticationProfileResponse &ns4__ModifyAuthenticationProfileResponse)
{	struct soap *soap = this->soap;
	struct __ns4__ModifyAuthenticationProfile soap_tmp___ns4__ModifyAuthenticationProfile;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/ModifyAuthenticationProfile";
	soap_tmp___ns4__ModifyAuthenticationProfile.ns4__ModifyAuthenticationProfile = ns4__ModifyAuthenticationProfile;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns4__ModifyAuthenticationProfile(soap, &soap_tmp___ns4__ModifyAuthenticationProfile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns4__ModifyAuthenticationProfile(soap, &soap_tmp___ns4__ModifyAuthenticationProfile, "-ns4:ModifyAuthenticationProfile", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns4__ModifyAuthenticationProfile(soap, &soap_tmp___ns4__ModifyAuthenticationProfile, "-ns4:ModifyAuthenticationProfile", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns4__ModifyAuthenticationProfileResponse*>(&ns4__ModifyAuthenticationProfileResponse)) // NULL ref?
		return soap_closesock(soap);
	ns4__ModifyAuthenticationProfileResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns4__ModifyAuthenticationProfileResponse.soap_get(soap, "ns4:ModifyAuthenticationProfileResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::DeleteAuthenticationProfile(const char *endpoint, const char *soap_action, _ns4__DeleteAuthenticationProfile *ns4__DeleteAuthenticationProfile, _ns4__DeleteAuthenticationProfileResponse &ns4__DeleteAuthenticationProfileResponse)
{	struct soap *soap = this->soap;
	struct __ns4__DeleteAuthenticationProfile soap_tmp___ns4__DeleteAuthenticationProfile;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/DeleteAuthenticationProfile";
	soap_tmp___ns4__DeleteAuthenticationProfile.ns4__DeleteAuthenticationProfile = ns4__DeleteAuthenticationProfile;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns4__DeleteAuthenticationProfile(soap, &soap_tmp___ns4__DeleteAuthenticationProfile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns4__DeleteAuthenticationProfile(soap, &soap_tmp___ns4__DeleteAuthenticationProfile, "-ns4:DeleteAuthenticationProfile", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns4__DeleteAuthenticationProfile(soap, &soap_tmp___ns4__DeleteAuthenticationProfile, "-ns4:DeleteAuthenticationProfile", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns4__DeleteAuthenticationProfileResponse*>(&ns4__DeleteAuthenticationProfileResponse)) // NULL ref?
		return soap_closesock(soap);
	ns4__DeleteAuthenticationProfileResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns4__DeleteAuthenticationProfileResponse.soap_get(soap, "ns4:DeleteAuthenticationProfileResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::GetSecurityLevelInfo(const char *endpoint, const char *soap_action, _ns4__GetSecurityLevelInfo *ns4__GetSecurityLevelInfo, _ns4__GetSecurityLevelInfoResponse &ns4__GetSecurityLevelInfoResponse)
{	struct soap *soap = this->soap;
	struct __ns4__GetSecurityLevelInfo soap_tmp___ns4__GetSecurityLevelInfo;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetSecurityLevelInfo";
	soap_tmp___ns4__GetSecurityLevelInfo.ns4__GetSecurityLevelInfo = ns4__GetSecurityLevelInfo;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns4__GetSecurityLevelInfo(soap, &soap_tmp___ns4__GetSecurityLevelInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns4__GetSecurityLevelInfo(soap, &soap_tmp___ns4__GetSecurityLevelInfo, "-ns4:GetSecurityLevelInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns4__GetSecurityLevelInfo(soap, &soap_tmp___ns4__GetSecurityLevelInfo, "-ns4:GetSecurityLevelInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns4__GetSecurityLevelInfoResponse*>(&ns4__GetSecurityLevelInfoResponse)) // NULL ref?
		return soap_closesock(soap);
	ns4__GetSecurityLevelInfoResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns4__GetSecurityLevelInfoResponse.soap_get(soap, "ns4:GetSecurityLevelInfoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::GetSecurityLevelInfoList(const char *endpoint, const char *soap_action, _ns4__GetSecurityLevelInfoList *ns4__GetSecurityLevelInfoList, _ns4__GetSecurityLevelInfoListResponse &ns4__GetSecurityLevelInfoListResponse)
{	struct soap *soap = this->soap;
	struct __ns4__GetSecurityLevelInfoList soap_tmp___ns4__GetSecurityLevelInfoList;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetSecurityLevelInfoList";
	soap_tmp___ns4__GetSecurityLevelInfoList.ns4__GetSecurityLevelInfoList = ns4__GetSecurityLevelInfoList;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns4__GetSecurityLevelInfoList(soap, &soap_tmp___ns4__GetSecurityLevelInfoList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns4__GetSecurityLevelInfoList(soap, &soap_tmp___ns4__GetSecurityLevelInfoList, "-ns4:GetSecurityLevelInfoList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns4__GetSecurityLevelInfoList(soap, &soap_tmp___ns4__GetSecurityLevelInfoList, "-ns4:GetSecurityLevelInfoList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns4__GetSecurityLevelInfoListResponse*>(&ns4__GetSecurityLevelInfoListResponse)) // NULL ref?
		return soap_closesock(soap);
	ns4__GetSecurityLevelInfoListResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns4__GetSecurityLevelInfoListResponse.soap_get(soap, "ns4:GetSecurityLevelInfoListResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::GetSecurityLevels(const char *endpoint, const char *soap_action, _ns4__GetSecurityLevels *ns4__GetSecurityLevels, _ns4__GetSecurityLevelsResponse &ns4__GetSecurityLevelsResponse)
{	struct soap *soap = this->soap;
	struct __ns4__GetSecurityLevels soap_tmp___ns4__GetSecurityLevels;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetSecurityLevels";
	soap_tmp___ns4__GetSecurityLevels.ns4__GetSecurityLevels = ns4__GetSecurityLevels;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns4__GetSecurityLevels(soap, &soap_tmp___ns4__GetSecurityLevels);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns4__GetSecurityLevels(soap, &soap_tmp___ns4__GetSecurityLevels, "-ns4:GetSecurityLevels", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns4__GetSecurityLevels(soap, &soap_tmp___ns4__GetSecurityLevels, "-ns4:GetSecurityLevels", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns4__GetSecurityLevelsResponse*>(&ns4__GetSecurityLevelsResponse)) // NULL ref?
		return soap_closesock(soap);
	ns4__GetSecurityLevelsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns4__GetSecurityLevelsResponse.soap_get(soap, "ns4:GetSecurityLevelsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::GetSecurityLevelList(const char *endpoint, const char *soap_action, _ns4__GetSecurityLevelList *ns4__GetSecurityLevelList, _ns4__GetSecurityLevelListResponse &ns4__GetSecurityLevelListResponse)
{	struct soap *soap = this->soap;
	struct __ns4__GetSecurityLevelList soap_tmp___ns4__GetSecurityLevelList;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetSecurityLevelList";
	soap_tmp___ns4__GetSecurityLevelList.ns4__GetSecurityLevelList = ns4__GetSecurityLevelList;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns4__GetSecurityLevelList(soap, &soap_tmp___ns4__GetSecurityLevelList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns4__GetSecurityLevelList(soap, &soap_tmp___ns4__GetSecurityLevelList, "-ns4:GetSecurityLevelList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns4__GetSecurityLevelList(soap, &soap_tmp___ns4__GetSecurityLevelList, "-ns4:GetSecurityLevelList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns4__GetSecurityLevelListResponse*>(&ns4__GetSecurityLevelListResponse)) // NULL ref?
		return soap_closesock(soap);
	ns4__GetSecurityLevelListResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns4__GetSecurityLevelListResponse.soap_get(soap, "ns4:GetSecurityLevelListResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::CreateSecurityLevel(const char *endpoint, const char *soap_action, _ns4__CreateSecurityLevel *ns4__CreateSecurityLevel, _ns4__CreateSecurityLevelResponse &ns4__CreateSecurityLevelResponse)
{	struct soap *soap = this->soap;
	struct __ns4__CreateSecurityLevel soap_tmp___ns4__CreateSecurityLevel;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/CreateSecurityLevel";
	soap_tmp___ns4__CreateSecurityLevel.ns4__CreateSecurityLevel = ns4__CreateSecurityLevel;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns4__CreateSecurityLevel(soap, &soap_tmp___ns4__CreateSecurityLevel);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns4__CreateSecurityLevel(soap, &soap_tmp___ns4__CreateSecurityLevel, "-ns4:CreateSecurityLevel", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns4__CreateSecurityLevel(soap, &soap_tmp___ns4__CreateSecurityLevel, "-ns4:CreateSecurityLevel", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns4__CreateSecurityLevelResponse*>(&ns4__CreateSecurityLevelResponse)) // NULL ref?
		return soap_closesock(soap);
	ns4__CreateSecurityLevelResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns4__CreateSecurityLevelResponse.soap_get(soap, "ns4:CreateSecurityLevelResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::SetSecurityLevel(const char *endpoint, const char *soap_action, _ns4__SetSecurityLevel *ns4__SetSecurityLevel, _ns4__SetSecurityLevelResponse &ns4__SetSecurityLevelResponse)
{	struct soap *soap = this->soap;
	struct __ns4__SetSecurityLevel soap_tmp___ns4__SetSecurityLevel;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/SetSecurityLevel";
	soap_tmp___ns4__SetSecurityLevel.ns4__SetSecurityLevel = ns4__SetSecurityLevel;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns4__SetSecurityLevel(soap, &soap_tmp___ns4__SetSecurityLevel);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns4__SetSecurityLevel(soap, &soap_tmp___ns4__SetSecurityLevel, "-ns4:SetSecurityLevel", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns4__SetSecurityLevel(soap, &soap_tmp___ns4__SetSecurityLevel, "-ns4:SetSecurityLevel", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns4__SetSecurityLevelResponse*>(&ns4__SetSecurityLevelResponse)) // NULL ref?
		return soap_closesock(soap);
	ns4__SetSecurityLevelResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns4__SetSecurityLevelResponse.soap_get(soap, "ns4:SetSecurityLevelResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::ModifySecurityLevel(const char *endpoint, const char *soap_action, _ns4__ModifySecurityLevel *ns4__ModifySecurityLevel, _ns4__ModifySecurityLevelResponse &ns4__ModifySecurityLevelResponse)
{	struct soap *soap = this->soap;
	struct __ns4__ModifySecurityLevel soap_tmp___ns4__ModifySecurityLevel;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/ModifySecurityLevel";
	soap_tmp___ns4__ModifySecurityLevel.ns4__ModifySecurityLevel = ns4__ModifySecurityLevel;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns4__ModifySecurityLevel(soap, &soap_tmp___ns4__ModifySecurityLevel);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns4__ModifySecurityLevel(soap, &soap_tmp___ns4__ModifySecurityLevel, "-ns4:ModifySecurityLevel", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns4__ModifySecurityLevel(soap, &soap_tmp___ns4__ModifySecurityLevel, "-ns4:ModifySecurityLevel", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns4__ModifySecurityLevelResponse*>(&ns4__ModifySecurityLevelResponse)) // NULL ref?
		return soap_closesock(soap);
	ns4__ModifySecurityLevelResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns4__ModifySecurityLevelResponse.soap_get(soap, "ns4:ModifySecurityLevelResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::DeleteSecurityLevel(const char *endpoint, const char *soap_action, _ns4__DeleteSecurityLevel *ns4__DeleteSecurityLevel, _ns4__DeleteSecurityLevelResponse &ns4__DeleteSecurityLevelResponse)
{	struct soap *soap = this->soap;
	struct __ns4__DeleteSecurityLevel soap_tmp___ns4__DeleteSecurityLevel;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/DeleteSecurityLevel";
	soap_tmp___ns4__DeleteSecurityLevel.ns4__DeleteSecurityLevel = ns4__DeleteSecurityLevel;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns4__DeleteSecurityLevel(soap, &soap_tmp___ns4__DeleteSecurityLevel);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns4__DeleteSecurityLevel(soap, &soap_tmp___ns4__DeleteSecurityLevel, "-ns4:DeleteSecurityLevel", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns4__DeleteSecurityLevel(soap, &soap_tmp___ns4__DeleteSecurityLevel, "-ns4:DeleteSecurityLevel", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns4__DeleteSecurityLevelResponse*>(&ns4__DeleteSecurityLevelResponse)) // NULL ref?
		return soap_closesock(soap);
	ns4__DeleteSecurityLevelResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns4__DeleteSecurityLevelResponse.soap_get(soap, "ns4:DeleteSecurityLevelResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
