/* soapThermalBindingProxy.cpp
   Generated by gSOAP 2.8.45 for onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "soapThermalBindingProxy.h"

ThermalBindingProxy::ThermalBindingProxy()
{	this->soap = soap_new();
	this->soap_own = true;
	ThermalBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

ThermalBindingProxy::ThermalBindingProxy(const ThermalBindingProxy& rhs)
{	this->soap = rhs.soap;
	this->soap_own = false;
	this->soap_endpoint = rhs.soap_endpoint;
}

ThermalBindingProxy::ThermalBindingProxy(struct soap *_soap)
{	this->soap = _soap;
	this->soap_own = false;
	ThermalBindingProxy_init(_soap->imode, _soap->omode);
}

ThermalBindingProxy::ThermalBindingProxy(const char *endpoint)
{	this->soap = soap_new();
	this->soap_own = true;
	ThermalBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = endpoint;
}

ThermalBindingProxy::ThermalBindingProxy(soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	ThermalBindingProxy_init(iomode, iomode);
}

ThermalBindingProxy::ThermalBindingProxy(const char *endpoint, soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	ThermalBindingProxy_init(iomode, iomode);
	soap_endpoint = endpoint;
}

ThermalBindingProxy::ThermalBindingProxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->soap_own = true;
	ThermalBindingProxy_init(imode, omode);
}

ThermalBindingProxy::~ThermalBindingProxy()
{	if (this->soap_own)
		soap_free(this->soap);
}

void ThermalBindingProxy::ThermalBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] = {
        {"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
        {"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
        {"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
        {"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
        {"wsa", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL, NULL},
        {"wsdd", "http://schemas.xmlsoap.org/ws/2005/04/discovery", NULL, NULL},
        {"chan", "http://schemas.microsoft.com/ws/2005/02/duplex", NULL, NULL},
        {"wsa5", "http://www.w3.org/2005/08/addressing", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL},
        {"c14n", "http://www.w3.org/2001/10/xml-exc-c14n#", NULL, NULL},
        {"ds", "http://www.w3.org/2000/09/xmldsig#", NULL, NULL},
        {"saml1", "urn:oasis:names:tc:SAML:1.0:assertion", NULL, NULL},
        {"saml2", "urn:oasis:names:tc:SAML:2.0:assertion", NULL, NULL},
        {"wsu", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", NULL, NULL},
        {"xenc", "http://www.w3.org/2001/04/xmlenc#", NULL, NULL},
        {"wsc", "http://docs.oasis-open.org/ws-sx/ws-secureconversation/200512", NULL, NULL},
        {"wsse", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", "http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd", NULL},
        {"ns1", "http://www.onvif.org/ver20/analytics/humanface", NULL, NULL},
        {"ns2", "http://www.onvif.org/ver20/analytics/humanbody", NULL, NULL},
        {"ns5", "http://www.onvif.org/ver10/pacs", NULL, NULL},
        {"xmime", "http://tempuri.org/xmime.xsd", NULL, NULL},
        {"xop", "http://www.w3.org/2004/08/xop/include", NULL, NULL},
        {"tt", "http://www.onvif.org/ver10/schema", NULL, NULL},
        {"wsrfbf", "http://docs.oasis-open.org/wsrf/bf-2", NULL, NULL},
        {"wstop", "http://docs.oasis-open.org/wsn/t-1", NULL, NULL},
        {"wsrfr", "http://docs.oasis-open.org/wsrf/r-2", NULL, NULL},
        {"ns10", "http://www.onvif.org/ver10/schedule/wsdl", NULL, NULL},
        {"ns11", "http://www.onvif.org/ver10/thermal/wsdl", NULL, NULL},
        {"ns12", "http://www.onvif.org/ver10/uplink/wsdl", NULL, NULL},
        {"ns13", "http://www.onvif.org/ver10/accesscontrol/wsdl", NULL, NULL},
        {"ns14", "http://www.onvif.org/ver10/accessrules/wsdl", NULL, NULL},
        {"ns3", "http://www.onvif.org/ver10/actionengine/wsdl", NULL, NULL},
        {"ns4", "http://www.onvif.org/ver10/authenticationbehavior/wsdl", NULL, NULL},
        {"ns6", "http://www.onvif.org/ver10/credential/wsdl", NULL, NULL},
        {"ns7", "http://www.onvif.org/ver10/doorcontrol/wsdl", NULL, NULL},
        {"ns8", "http://www.onvif.org/ver20/media/wsdl", NULL, NULL},
        {"ns9", "http://www.onvif.org/ver10/provisioning/wsdl", NULL, NULL},
        {"tan", "http://www.onvif.org/ver20/analytics/wsdl", NULL, NULL},
        {"tas", "http://www.onvif.org/ver10/advancedsecurity/wsdl", NULL, NULL},
        {"tdn", "http://www.onvif.org/ver10/network/wsdl", NULL, NULL},
        {"tds", "http://www.onvif.org/ver10/device/wsdl", NULL, NULL},
        {"tev", "http://www.onvif.org/ver10/events/wsdl", NULL, NULL},
        {"wsnt", "http://docs.oasis-open.org/wsn/b-2", NULL, NULL},
        {"timg", "http://www.onvif.org/ver20/imaging/wsdl", NULL, NULL},
        {"tls", "http://www.onvif.org/ver10/display/wsdl", NULL, NULL},
        {"tmd", "http://www.onvif.org/ver10/deviceIO/wsdl", NULL, NULL},
        {"tptz", "http://www.onvif.org/ver20/ptz/wsdl", NULL, NULL},
        {"trc", "http://www.onvif.org/ver10/recording/wsdl", NULL, NULL},
        {"trp", "http://www.onvif.org/ver10/replay/wsdl", NULL, NULL},
        {"trt", "http://www.onvif.org/ver10/media/wsdl", NULL, NULL},
        {"trv", "http://www.onvif.org/ver10/receiver/wsdl", NULL, NULL},
        {"tse", "http://www.onvif.org/ver10/search/wsdl", NULL, NULL},
        {NULL, NULL, NULL, NULL}
    };
	soap_set_namespaces(this->soap, namespaces);
}

#ifndef WITH_PURE_VIRTUAL
ThermalBindingProxy *ThermalBindingProxy::copy()
{	ThermalBindingProxy *dup = SOAP_NEW_COPY(ThermalBindingProxy);
	if (dup)
		soap_copy_context(dup->soap, this->soap);
	return dup;
}
#endif

ThermalBindingProxy& ThermalBindingProxy::operator=(const ThermalBindingProxy& rhs)
{	if (this->soap_own)
		soap_free(this->soap);
	this->soap = rhs.soap;
	this->soap_own = false;
	this->soap_endpoint = rhs.soap_endpoint;
	return *this;
}

void ThermalBindingProxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void ThermalBindingProxy::reset()
{	this->destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	ThermalBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void ThermalBindingProxy::soap_noheader()
{	this->soap->header = NULL;
}

void ThermalBindingProxy::soap_header(char *wsa__MessageID, struct wsa__Relationship *wsa__RelatesTo, struct wsa__EndpointReferenceType *wsa__From, struct wsa__EndpointReferenceType *wsa__ReplyTo, struct wsa__EndpointReferenceType *wsa__FaultTo, char *wsa__To, char *wsa__Action, struct wsdd__AppSequenceType *wsdd__AppSequence, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct _wsse__Security *wsse__Security)
{	::soap_header(this->soap);
	this->soap->header->wsa__MessageID = wsa__MessageID;
	this->soap->header->wsa__RelatesTo = wsa__RelatesTo;
	this->soap->header->wsa__From = wsa__From;
	this->soap->header->wsa__ReplyTo = wsa__ReplyTo;
	this->soap->header->wsa__FaultTo = wsa__FaultTo;
	this->soap->header->wsa__To = wsa__To;
	this->soap->header->wsa__Action = wsa__Action;
	this->soap->header->wsdd__AppSequence = wsdd__AppSequence;
	this->soap->header->wsa5__MessageID = wsa5__MessageID;
	this->soap->header->wsa5__RelatesTo = wsa5__RelatesTo;
	this->soap->header->wsa5__From = wsa5__From;
	this->soap->header->wsa5__ReplyTo = wsa5__ReplyTo;
	this->soap->header->wsa5__FaultTo = wsa5__FaultTo;
	this->soap->header->wsa5__To = wsa5__To;
	this->soap->header->wsa5__Action = wsa5__Action;
	this->soap->header->chan__ChannelInstance = chan__ChannelInstance;
	this->soap->header->wsse__Security = wsse__Security;
}

::SOAP_ENV__Header *ThermalBindingProxy::soap_header()
{	return this->soap->header;
}

::SOAP_ENV__Fault *ThermalBindingProxy::soap_fault()
{	return this->soap->fault;
}

const char *ThermalBindingProxy::soap_fault_string()
{	return *soap_faultstring(this->soap);
}

const char *ThermalBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this->soap);
}

int ThermalBindingProxy::soap_close_socket()
{	return soap_closesock(this->soap);
}

int ThermalBindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

void ThermalBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void ThermalBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *ThermalBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int ThermalBindingProxy::GetServiceCapabilities(const char *endpoint, const char *soap_action, _ns11__GetServiceCapabilities *ns11__GetServiceCapabilities, _ns11__GetServiceCapabilitiesResponse &ns11__GetServiceCapabilitiesResponse)
{	struct soap *soap = this->soap;
	struct __ns11__GetServiceCapabilities soap_tmp___ns11__GetServiceCapabilities;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/thermal/wsdl/GetServiceCapabilities";
	soap_tmp___ns11__GetServiceCapabilities.ns11__GetServiceCapabilities = ns11__GetServiceCapabilities;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns11__GetServiceCapabilities(soap, &soap_tmp___ns11__GetServiceCapabilities);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns11__GetServiceCapabilities(soap, &soap_tmp___ns11__GetServiceCapabilities, "-ns11:GetServiceCapabilities", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns11__GetServiceCapabilities(soap, &soap_tmp___ns11__GetServiceCapabilities, "-ns11:GetServiceCapabilities", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns11__GetServiceCapabilitiesResponse*>(&ns11__GetServiceCapabilitiesResponse)) // NULL ref?
		return soap_closesock(soap);
	ns11__GetServiceCapabilitiesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns11__GetServiceCapabilitiesResponse.soap_get(soap, "ns11:GetServiceCapabilitiesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ThermalBindingProxy::GetConfigurationOptions(const char *endpoint, const char *soap_action, _ns11__GetConfigurationOptions *ns11__GetConfigurationOptions, _ns11__GetConfigurationOptionsResponse &ns11__GetConfigurationOptionsResponse)
{	struct soap *soap = this->soap;
	struct __ns11__GetConfigurationOptions soap_tmp___ns11__GetConfigurationOptions;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/thermal/wsdl/GetConfigurationOptions";
	soap_tmp___ns11__GetConfigurationOptions.ns11__GetConfigurationOptions = ns11__GetConfigurationOptions;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns11__GetConfigurationOptions(soap, &soap_tmp___ns11__GetConfigurationOptions);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns11__GetConfigurationOptions(soap, &soap_tmp___ns11__GetConfigurationOptions, "-ns11:GetConfigurationOptions", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns11__GetConfigurationOptions(soap, &soap_tmp___ns11__GetConfigurationOptions, "-ns11:GetConfigurationOptions", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns11__GetConfigurationOptionsResponse*>(&ns11__GetConfigurationOptionsResponse)) // NULL ref?
		return soap_closesock(soap);
	ns11__GetConfigurationOptionsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns11__GetConfigurationOptionsResponse.soap_get(soap, "ns11:GetConfigurationOptionsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ThermalBindingProxy::GetConfiguration(const char *endpoint, const char *soap_action, _ns11__GetConfiguration *ns11__GetConfiguration, _ns11__GetConfigurationResponse &ns11__GetConfigurationResponse)
{	struct soap *soap = this->soap;
	struct __ns11__GetConfiguration soap_tmp___ns11__GetConfiguration;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/thermal/wsdl/GetConfiguration";
	soap_tmp___ns11__GetConfiguration.ns11__GetConfiguration = ns11__GetConfiguration;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns11__GetConfiguration(soap, &soap_tmp___ns11__GetConfiguration);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns11__GetConfiguration(soap, &soap_tmp___ns11__GetConfiguration, "-ns11:GetConfiguration", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns11__GetConfiguration(soap, &soap_tmp___ns11__GetConfiguration, "-ns11:GetConfiguration", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns11__GetConfigurationResponse*>(&ns11__GetConfigurationResponse)) // NULL ref?
		return soap_closesock(soap);
	ns11__GetConfigurationResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns11__GetConfigurationResponse.soap_get(soap, "ns11:GetConfigurationResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ThermalBindingProxy::GetConfigurations(const char *endpoint, const char *soap_action, _ns11__GetConfigurations *ns11__GetConfigurations, _ns11__GetConfigurationsResponse &ns11__GetConfigurationsResponse)
{	struct soap *soap = this->soap;
	struct __ns11__GetConfigurations soap_tmp___ns11__GetConfigurations;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/thermal/wsdl/GetConfigurations";
	soap_tmp___ns11__GetConfigurations.ns11__GetConfigurations = ns11__GetConfigurations;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns11__GetConfigurations(soap, &soap_tmp___ns11__GetConfigurations);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns11__GetConfigurations(soap, &soap_tmp___ns11__GetConfigurations, "-ns11:GetConfigurations", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns11__GetConfigurations(soap, &soap_tmp___ns11__GetConfigurations, "-ns11:GetConfigurations", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns11__GetConfigurationsResponse*>(&ns11__GetConfigurationsResponse)) // NULL ref?
		return soap_closesock(soap);
	ns11__GetConfigurationsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns11__GetConfigurationsResponse.soap_get(soap, "ns11:GetConfigurationsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ThermalBindingProxy::SetConfiguration(const char *endpoint, const char *soap_action, _ns11__SetConfiguration *ns11__SetConfiguration, _ns11__SetConfigurationResponse &ns11__SetConfigurationResponse)
{	struct soap *soap = this->soap;
	struct __ns11__SetConfiguration soap_tmp___ns11__SetConfiguration;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/thermal/wsdl/SetConfiguration";
	soap_tmp___ns11__SetConfiguration.ns11__SetConfiguration = ns11__SetConfiguration;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns11__SetConfiguration(soap, &soap_tmp___ns11__SetConfiguration);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns11__SetConfiguration(soap, &soap_tmp___ns11__SetConfiguration, "-ns11:SetConfiguration", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns11__SetConfiguration(soap, &soap_tmp___ns11__SetConfiguration, "-ns11:SetConfiguration", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns11__SetConfigurationResponse*>(&ns11__SetConfigurationResponse)) // NULL ref?
		return soap_closesock(soap);
	ns11__SetConfigurationResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns11__SetConfigurationResponse.soap_get(soap, "ns11:SetConfigurationResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ThermalBindingProxy::GetRadiometryConfigurationOptions(const char *endpoint, const char *soap_action, _ns11__GetRadiometryConfigurationOptions *ns11__GetRadiometryConfigurationOptions, _ns11__GetRadiometryConfigurationOptionsResponse &ns11__GetRadiometryConfigurationOptionsResponse)
{	struct soap *soap = this->soap;
	struct __ns11__GetRadiometryConfigurationOptions soap_tmp___ns11__GetRadiometryConfigurationOptions;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/thermal/wsdl/GetRadiometryConfigurationOptions";
	soap_tmp___ns11__GetRadiometryConfigurationOptions.ns11__GetRadiometryConfigurationOptions = ns11__GetRadiometryConfigurationOptions;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns11__GetRadiometryConfigurationOptions(soap, &soap_tmp___ns11__GetRadiometryConfigurationOptions);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns11__GetRadiometryConfigurationOptions(soap, &soap_tmp___ns11__GetRadiometryConfigurationOptions, "-ns11:GetRadiometryConfigurationOptions", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns11__GetRadiometryConfigurationOptions(soap, &soap_tmp___ns11__GetRadiometryConfigurationOptions, "-ns11:GetRadiometryConfigurationOptions", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns11__GetRadiometryConfigurationOptionsResponse*>(&ns11__GetRadiometryConfigurationOptionsResponse)) // NULL ref?
		return soap_closesock(soap);
	ns11__GetRadiometryConfigurationOptionsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns11__GetRadiometryConfigurationOptionsResponse.soap_get(soap, "ns11:GetRadiometryConfigurationOptionsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ThermalBindingProxy::GetRadiometryConfiguration(const char *endpoint, const char *soap_action, _ns11__GetRadiometryConfiguration *ns11__GetRadiometryConfiguration, _ns11__GetRadiometryConfigurationResponse &ns11__GetRadiometryConfigurationResponse)
{	struct soap *soap = this->soap;
	struct __ns11__GetRadiometryConfiguration soap_tmp___ns11__GetRadiometryConfiguration;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/thermal/wsdl/GetRadiometryConfiguration";
	soap_tmp___ns11__GetRadiometryConfiguration.ns11__GetRadiometryConfiguration = ns11__GetRadiometryConfiguration;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns11__GetRadiometryConfiguration(soap, &soap_tmp___ns11__GetRadiometryConfiguration);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns11__GetRadiometryConfiguration(soap, &soap_tmp___ns11__GetRadiometryConfiguration, "-ns11:GetRadiometryConfiguration", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns11__GetRadiometryConfiguration(soap, &soap_tmp___ns11__GetRadiometryConfiguration, "-ns11:GetRadiometryConfiguration", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns11__GetRadiometryConfigurationResponse*>(&ns11__GetRadiometryConfigurationResponse)) // NULL ref?
		return soap_closesock(soap);
	ns11__GetRadiometryConfigurationResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns11__GetRadiometryConfigurationResponse.soap_get(soap, "ns11:GetRadiometryConfigurationResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ThermalBindingProxy::SetRadiometryConfiguration(const char *endpoint, const char *soap_action, _ns11__SetRadiometryConfiguration *ns11__SetRadiometryConfiguration, _ns11__SetRadiometryConfigurationResponse &ns11__SetRadiometryConfigurationResponse)
{	struct soap *soap = this->soap;
	struct __ns11__SetRadiometryConfiguration soap_tmp___ns11__SetRadiometryConfiguration;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/thermal/wsdl/SetRadiometryConfiguration";
	soap_tmp___ns11__SetRadiometryConfiguration.ns11__SetRadiometryConfiguration = ns11__SetRadiometryConfiguration;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns11__SetRadiometryConfiguration(soap, &soap_tmp___ns11__SetRadiometryConfiguration);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns11__SetRadiometryConfiguration(soap, &soap_tmp___ns11__SetRadiometryConfiguration, "-ns11:SetRadiometryConfiguration", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns11__SetRadiometryConfiguration(soap, &soap_tmp___ns11__SetRadiometryConfiguration, "-ns11:SetRadiometryConfiguration", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns11__SetRadiometryConfigurationResponse*>(&ns11__SetRadiometryConfigurationResponse)) // NULL ref?
		return soap_closesock(soap);
	ns11__SetRadiometryConfigurationResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns11__SetRadiometryConfigurationResponse.soap_get(soap, "ns11:SetRadiometryConfigurationResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
