/* soapActionEngineBindingProxy.h
   Generated by gSOAP 2.8.45 for onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapActionEngineBindingProxy_H
#define soapActionEngineBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC ActionEngineBindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        bool soap_own; ///< flag indicating that this context is owned by this proxy when context is shared
        /// Endpoint URL of service 'ActionEngineBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in onvif.h, if any
        /// Construct a proxy with new managing context
        ActionEngineBindingProxy();
        /// Copy constructor
        ActionEngineBindingProxy(const ActionEngineBindingProxy& rhs);
        /// Construct proxy given a shared managing context
        ActionEngineBindingProxy(struct soap*);
        /// Constructor taking an endpoint URL
        ActionEngineBindingProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        ActionEngineBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        ActionEngineBindingProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        ActionEngineBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes non-shared managing context only (use destroy() to delete deserialized data)
        virtual ~ActionEngineBindingProxy();
        /// Initializer used by constructors
        virtual void ActionEngineBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual ActionEngineBindingProxy *copy() SOAP_PURE_VIRTUAL;
        /// Copy assignment
        ActionEngineBindingProxy& operator=(const ActionEngineBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Add SOAP Header to message
        virtual void soap_header(char *wsa__MessageID, struct wsa__Relationship *wsa__RelatesTo, struct wsa__EndpointReferenceType *wsa__From, struct wsa__EndpointReferenceType *wsa__ReplyTo, struct wsa__EndpointReferenceType *wsa__FaultTo, char *wsa__To, char *wsa__Action, struct wsdd__AppSequenceType *wsdd__AppSequence, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct _wsse__Security *wsse__Security);
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault string (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail as string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'GetSupportedActions' (returns SOAP_OK or error code)
        virtual int GetSupportedActions(_ns3__GetSupportedActions *ns3__GetSupportedActions, _ns3__GetSupportedActionsResponse &ns3__GetSupportedActionsResponse)
        { return this->GetSupportedActions(NULL, NULL, ns3__GetSupportedActions, ns3__GetSupportedActionsResponse); }
        virtual int GetSupportedActions(const char *soap_endpoint, const char *soap_action, _ns3__GetSupportedActions *ns3__GetSupportedActions, _ns3__GetSupportedActionsResponse &ns3__GetSupportedActionsResponse);
        /// Web service operation 'GetActions' (returns SOAP_OK or error code)
        virtual int GetActions(_ns3__GetActions *ns3__GetActions, _ns3__GetActionsResponse &ns3__GetActionsResponse)
        { return this->GetActions(NULL, NULL, ns3__GetActions, ns3__GetActionsResponse); }
        virtual int GetActions(const char *soap_endpoint, const char *soap_action, _ns3__GetActions *ns3__GetActions, _ns3__GetActionsResponse &ns3__GetActionsResponse);
        /// Web service operation 'CreateActions' (returns SOAP_OK or error code)
        virtual int CreateActions(_ns3__CreateActions *ns3__CreateActions, _ns3__CreateActionsResponse &ns3__CreateActionsResponse)
        { return this->CreateActions(NULL, NULL, ns3__CreateActions, ns3__CreateActionsResponse); }
        virtual int CreateActions(const char *soap_endpoint, const char *soap_action, _ns3__CreateActions *ns3__CreateActions, _ns3__CreateActionsResponse &ns3__CreateActionsResponse);
        /// Web service operation 'DeleteActions' (returns SOAP_OK or error code)
        virtual int DeleteActions(_ns3__DeleteActions *ns3__DeleteActions, _ns3__DeleteActionsResponse &ns3__DeleteActionsResponse)
        { return this->DeleteActions(NULL, NULL, ns3__DeleteActions, ns3__DeleteActionsResponse); }
        virtual int DeleteActions(const char *soap_endpoint, const char *soap_action, _ns3__DeleteActions *ns3__DeleteActions, _ns3__DeleteActionsResponse &ns3__DeleteActionsResponse);
        /// Web service operation 'ModifyActions' (returns SOAP_OK or error code)
        virtual int ModifyActions(_ns3__ModifyActions *ns3__ModifyActions, _ns3__ModifyActionsResponse &ns3__ModifyActionsResponse)
        { return this->ModifyActions(NULL, NULL, ns3__ModifyActions, ns3__ModifyActionsResponse); }
        virtual int ModifyActions(const char *soap_endpoint, const char *soap_action, _ns3__ModifyActions *ns3__ModifyActions, _ns3__ModifyActionsResponse &ns3__ModifyActionsResponse);
        /// Web service operation 'GetServiceCapabilities' (returns SOAP_OK or error code)
        virtual int GetServiceCapabilities(_ns3__GetServiceCapabilities *ns3__GetServiceCapabilities, _ns3__GetServiceCapabilitiesResponse &ns3__GetServiceCapabilitiesResponse)
        { return this->GetServiceCapabilities(NULL, NULL, ns3__GetServiceCapabilities, ns3__GetServiceCapabilitiesResponse); }
        virtual int GetServiceCapabilities(const char *soap_endpoint, const char *soap_action, _ns3__GetServiceCapabilities *ns3__GetServiceCapabilities, _ns3__GetServiceCapabilitiesResponse &ns3__GetServiceCapabilitiesResponse);
        /// Web service operation 'GetActionTriggers' (returns SOAP_OK or error code)
        virtual int GetActionTriggers(_ns3__GetActionTriggers *ns3__GetActionTriggers, _ns3__GetActionTriggersResponse &ns3__GetActionTriggersResponse)
        { return this->GetActionTriggers(NULL, NULL, ns3__GetActionTriggers, ns3__GetActionTriggersResponse); }
        virtual int GetActionTriggers(const char *soap_endpoint, const char *soap_action, _ns3__GetActionTriggers *ns3__GetActionTriggers, _ns3__GetActionTriggersResponse &ns3__GetActionTriggersResponse);
        /// Web service operation 'CreateActionTriggers' (returns SOAP_OK or error code)
        virtual int CreateActionTriggers(_ns3__CreateActionTriggers *ns3__CreateActionTriggers, _ns3__CreateActionTriggersResponse &ns3__CreateActionTriggersResponse)
        { return this->CreateActionTriggers(NULL, NULL, ns3__CreateActionTriggers, ns3__CreateActionTriggersResponse); }
        virtual int CreateActionTriggers(const char *soap_endpoint, const char *soap_action, _ns3__CreateActionTriggers *ns3__CreateActionTriggers, _ns3__CreateActionTriggersResponse &ns3__CreateActionTriggersResponse);
        /// Web service operation 'DeleteActionTriggers' (returns SOAP_OK or error code)
        virtual int DeleteActionTriggers(_ns3__DeleteActionTriggers *ns3__DeleteActionTriggers, _ns3__DeleteActionTriggersResponse &ns3__DeleteActionTriggersResponse)
        { return this->DeleteActionTriggers(NULL, NULL, ns3__DeleteActionTriggers, ns3__DeleteActionTriggersResponse); }
        virtual int DeleteActionTriggers(const char *soap_endpoint, const char *soap_action, _ns3__DeleteActionTriggers *ns3__DeleteActionTriggers, _ns3__DeleteActionTriggersResponse &ns3__DeleteActionTriggersResponse);
        /// Web service operation 'ModifyActionTriggers' (returns SOAP_OK or error code)
        virtual int ModifyActionTriggers(_ns3__ModifyActionTriggers *ns3__ModifyActionTriggers, _ns3__ModifyActionTriggersResponse &ns3__ModifyActionTriggersResponse)
        { return this->ModifyActionTriggers(NULL, NULL, ns3__ModifyActionTriggers, ns3__ModifyActionTriggersResponse); }
        virtual int ModifyActionTriggers(const char *soap_endpoint, const char *soap_action, _ns3__ModifyActionTriggers *ns3__ModifyActionTriggers, _ns3__ModifyActionTriggersResponse &ns3__ModifyActionTriggersResponse);
    };
#endif
