/* soapPACSBindingProxy.h
   Generated by gSOAP 2.8.45 for onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapPACSBindingProxy_H
#define soapPACSBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC PACSBindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        bool soap_own; ///< flag indicating that this context is owned by this proxy when context is shared
        /// Endpoint URL of service 'PACSBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in onvif.h, if any
        /// Construct a proxy with new managing context
        PACSBindingProxy();
        /// Copy constructor
        PACSBindingProxy(const PACSBindingProxy& rhs);
        /// Construct proxy given a shared managing context
        PACSBindingProxy(struct soap*);
        /// Constructor taking an endpoint URL
        PACSBindingProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        PACSBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        PACSBindingProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        PACSBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes non-shared managing context only (use destroy() to delete deserialized data)
        virtual ~PACSBindingProxy();
        /// Initializer used by constructors
        virtual void PACSBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual PACSBindingProxy *copy() SOAP_PURE_VIRTUAL;
        /// Copy assignment
        PACSBindingProxy& operator=(const PACSBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Add SOAP Header to message
        virtual void soap_header(char *wsa__MessageID, struct wsa__Relationship *wsa__RelatesTo, struct wsa__EndpointReferenceType *wsa__From, struct wsa__EndpointReferenceType *wsa__ReplyTo, struct wsa__EndpointReferenceType *wsa__FaultTo, char *wsa__To, char *wsa__Action, struct wsdd__AppSequenceType *wsdd__AppSequence, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct _wsse__Security *wsse__Security);
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault string (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail as string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'GetServiceCapabilities' (returns SOAP_OK or error code)
        virtual int GetServiceCapabilities(_ns13__GetServiceCapabilities *ns13__GetServiceCapabilities, _ns13__GetServiceCapabilitiesResponse &ns13__GetServiceCapabilitiesResponse)
        { return this->GetServiceCapabilities(NULL, NULL, ns13__GetServiceCapabilities, ns13__GetServiceCapabilitiesResponse); }
        virtual int GetServiceCapabilities(const char *soap_endpoint, const char *soap_action, _ns13__GetServiceCapabilities *ns13__GetServiceCapabilities, _ns13__GetServiceCapabilitiesResponse &ns13__GetServiceCapabilitiesResponse);
        /// Web service operation 'GetAccessPointInfoList' (returns SOAP_OK or error code)
        virtual int GetAccessPointInfoList(_ns13__GetAccessPointInfoList *ns13__GetAccessPointInfoList, _ns13__GetAccessPointInfoListResponse &ns13__GetAccessPointInfoListResponse)
        { return this->GetAccessPointInfoList(NULL, NULL, ns13__GetAccessPointInfoList, ns13__GetAccessPointInfoListResponse); }
        virtual int GetAccessPointInfoList(const char *soap_endpoint, const char *soap_action, _ns13__GetAccessPointInfoList *ns13__GetAccessPointInfoList, _ns13__GetAccessPointInfoListResponse &ns13__GetAccessPointInfoListResponse);
        /// Web service operation 'GetAccessPointInfo' (returns SOAP_OK or error code)
        virtual int GetAccessPointInfo(_ns13__GetAccessPointInfo *ns13__GetAccessPointInfo, _ns13__GetAccessPointInfoResponse &ns13__GetAccessPointInfoResponse)
        { return this->GetAccessPointInfo(NULL, NULL, ns13__GetAccessPointInfo, ns13__GetAccessPointInfoResponse); }
        virtual int GetAccessPointInfo(const char *soap_endpoint, const char *soap_action, _ns13__GetAccessPointInfo *ns13__GetAccessPointInfo, _ns13__GetAccessPointInfoResponse &ns13__GetAccessPointInfoResponse);
        /// Web service operation 'GetAccessPointList' (returns SOAP_OK or error code)
        virtual int GetAccessPointList(_ns13__GetAccessPointList *ns13__GetAccessPointList, _ns13__GetAccessPointListResponse &ns13__GetAccessPointListResponse)
        { return this->GetAccessPointList(NULL, NULL, ns13__GetAccessPointList, ns13__GetAccessPointListResponse); }
        virtual int GetAccessPointList(const char *soap_endpoint, const char *soap_action, _ns13__GetAccessPointList *ns13__GetAccessPointList, _ns13__GetAccessPointListResponse &ns13__GetAccessPointListResponse);
        /// Web service operation 'GetAccessPoints' (returns SOAP_OK or error code)
        virtual int GetAccessPoints(_ns13__GetAccessPoints *ns13__GetAccessPoints, _ns13__GetAccessPointsResponse &ns13__GetAccessPointsResponse)
        { return this->GetAccessPoints(NULL, NULL, ns13__GetAccessPoints, ns13__GetAccessPointsResponse); }
        virtual int GetAccessPoints(const char *soap_endpoint, const char *soap_action, _ns13__GetAccessPoints *ns13__GetAccessPoints, _ns13__GetAccessPointsResponse &ns13__GetAccessPointsResponse);
        /// Web service operation 'CreateAccessPoint' (returns SOAP_OK or error code)
        virtual int CreateAccessPoint(_ns13__CreateAccessPoint *ns13__CreateAccessPoint, _ns13__CreateAccessPointResponse &ns13__CreateAccessPointResponse)
        { return this->CreateAccessPoint(NULL, NULL, ns13__CreateAccessPoint, ns13__CreateAccessPointResponse); }
        virtual int CreateAccessPoint(const char *soap_endpoint, const char *soap_action, _ns13__CreateAccessPoint *ns13__CreateAccessPoint, _ns13__CreateAccessPointResponse &ns13__CreateAccessPointResponse);
        /// Web service operation 'SetAccessPoint' (returns SOAP_OK or error code)
        virtual int SetAccessPoint(_ns13__SetAccessPoint *ns13__SetAccessPoint, _ns13__SetAccessPointResponse &ns13__SetAccessPointResponse)
        { return this->SetAccessPoint(NULL, NULL, ns13__SetAccessPoint, ns13__SetAccessPointResponse); }
        virtual int SetAccessPoint(const char *soap_endpoint, const char *soap_action, _ns13__SetAccessPoint *ns13__SetAccessPoint, _ns13__SetAccessPointResponse &ns13__SetAccessPointResponse);
        /// Web service operation 'ModifyAccessPoint' (returns SOAP_OK or error code)
        virtual int ModifyAccessPoint(_ns13__ModifyAccessPoint *ns13__ModifyAccessPoint, _ns13__ModifyAccessPointResponse &ns13__ModifyAccessPointResponse)
        { return this->ModifyAccessPoint(NULL, NULL, ns13__ModifyAccessPoint, ns13__ModifyAccessPointResponse); }
        virtual int ModifyAccessPoint(const char *soap_endpoint, const char *soap_action, _ns13__ModifyAccessPoint *ns13__ModifyAccessPoint, _ns13__ModifyAccessPointResponse &ns13__ModifyAccessPointResponse);
        /// Web service operation 'DeleteAccessPoint' (returns SOAP_OK or error code)
        virtual int DeleteAccessPoint(_ns13__DeleteAccessPoint *ns13__DeleteAccessPoint, _ns13__DeleteAccessPointResponse &ns13__DeleteAccessPointResponse)
        { return this->DeleteAccessPoint(NULL, NULL, ns13__DeleteAccessPoint, ns13__DeleteAccessPointResponse); }
        virtual int DeleteAccessPoint(const char *soap_endpoint, const char *soap_action, _ns13__DeleteAccessPoint *ns13__DeleteAccessPoint, _ns13__DeleteAccessPointResponse &ns13__DeleteAccessPointResponse);
        /// Web service operation 'SetAccessPointAuthenticationProfile' (returns SOAP_OK or error code)
        virtual int SetAccessPointAuthenticationProfile(_ns13__SetAccessPointAuthenticationProfile *ns13__SetAccessPointAuthenticationProfile, _ns13__SetAccessPointAuthenticationProfileResponse &ns13__SetAccessPointAuthenticationProfileResponse)
        { return this->SetAccessPointAuthenticationProfile(NULL, NULL, ns13__SetAccessPointAuthenticationProfile, ns13__SetAccessPointAuthenticationProfileResponse); }
        virtual int SetAccessPointAuthenticationProfile(const char *soap_endpoint, const char *soap_action, _ns13__SetAccessPointAuthenticationProfile *ns13__SetAccessPointAuthenticationProfile, _ns13__SetAccessPointAuthenticationProfileResponse &ns13__SetAccessPointAuthenticationProfileResponse);
        /// Web service operation 'DeleteAccessPointAuthenticationProfile' (returns SOAP_OK or error code)
        virtual int DeleteAccessPointAuthenticationProfile(_ns13__DeleteAccessPointAuthenticationProfile *ns13__DeleteAccessPointAuthenticationProfile, _ns13__DeleteAccessPointAuthenticationProfileResponse &ns13__DeleteAccessPointAuthenticationProfileResponse)
        { return this->DeleteAccessPointAuthenticationProfile(NULL, NULL, ns13__DeleteAccessPointAuthenticationProfile, ns13__DeleteAccessPointAuthenticationProfileResponse); }
        virtual int DeleteAccessPointAuthenticationProfile(const char *soap_endpoint, const char *soap_action, _ns13__DeleteAccessPointAuthenticationProfile *ns13__DeleteAccessPointAuthenticationProfile, _ns13__DeleteAccessPointAuthenticationProfileResponse &ns13__DeleteAccessPointAuthenticationProfileResponse);
        /// Web service operation 'GetAreaInfoList' (returns SOAP_OK or error code)
        virtual int GetAreaInfoList(_ns13__GetAreaInfoList *ns13__GetAreaInfoList, _ns13__GetAreaInfoListResponse &ns13__GetAreaInfoListResponse)
        { return this->GetAreaInfoList(NULL, NULL, ns13__GetAreaInfoList, ns13__GetAreaInfoListResponse); }
        virtual int GetAreaInfoList(const char *soap_endpoint, const char *soap_action, _ns13__GetAreaInfoList *ns13__GetAreaInfoList, _ns13__GetAreaInfoListResponse &ns13__GetAreaInfoListResponse);
        /// Web service operation 'GetAreaInfo' (returns SOAP_OK or error code)
        virtual int GetAreaInfo(_ns13__GetAreaInfo *ns13__GetAreaInfo, _ns13__GetAreaInfoResponse &ns13__GetAreaInfoResponse)
        { return this->GetAreaInfo(NULL, NULL, ns13__GetAreaInfo, ns13__GetAreaInfoResponse); }
        virtual int GetAreaInfo(const char *soap_endpoint, const char *soap_action, _ns13__GetAreaInfo *ns13__GetAreaInfo, _ns13__GetAreaInfoResponse &ns13__GetAreaInfoResponse);
        /// Web service operation 'GetAreaList' (returns SOAP_OK or error code)
        virtual int GetAreaList(_ns13__GetAreaList *ns13__GetAreaList, _ns13__GetAreaListResponse &ns13__GetAreaListResponse)
        { return this->GetAreaList(NULL, NULL, ns13__GetAreaList, ns13__GetAreaListResponse); }
        virtual int GetAreaList(const char *soap_endpoint, const char *soap_action, _ns13__GetAreaList *ns13__GetAreaList, _ns13__GetAreaListResponse &ns13__GetAreaListResponse);
        /// Web service operation 'GetAreas' (returns SOAP_OK or error code)
        virtual int GetAreas(_ns13__GetAreas *ns13__GetAreas, _ns13__GetAreasResponse &ns13__GetAreasResponse)
        { return this->GetAreas(NULL, NULL, ns13__GetAreas, ns13__GetAreasResponse); }
        virtual int GetAreas(const char *soap_endpoint, const char *soap_action, _ns13__GetAreas *ns13__GetAreas, _ns13__GetAreasResponse &ns13__GetAreasResponse);
        /// Web service operation 'CreateArea' (returns SOAP_OK or error code)
        virtual int CreateArea(_ns13__CreateArea *ns13__CreateArea, _ns13__CreateAreaResponse &ns13__CreateAreaResponse)
        { return this->CreateArea(NULL, NULL, ns13__CreateArea, ns13__CreateAreaResponse); }
        virtual int CreateArea(const char *soap_endpoint, const char *soap_action, _ns13__CreateArea *ns13__CreateArea, _ns13__CreateAreaResponse &ns13__CreateAreaResponse);
        /// Web service operation 'SetArea' (returns SOAP_OK or error code)
        virtual int SetArea(_ns13__SetArea *ns13__SetArea, _ns13__SetAreaResponse &ns13__SetAreaResponse)
        { return this->SetArea(NULL, NULL, ns13__SetArea, ns13__SetAreaResponse); }
        virtual int SetArea(const char *soap_endpoint, const char *soap_action, _ns13__SetArea *ns13__SetArea, _ns13__SetAreaResponse &ns13__SetAreaResponse);
        /// Web service operation 'ModifyArea' (returns SOAP_OK or error code)
        virtual int ModifyArea(_ns13__ModifyArea *ns13__ModifyArea, _ns13__ModifyAreaResponse &ns13__ModifyAreaResponse)
        { return this->ModifyArea(NULL, NULL, ns13__ModifyArea, ns13__ModifyAreaResponse); }
        virtual int ModifyArea(const char *soap_endpoint, const char *soap_action, _ns13__ModifyArea *ns13__ModifyArea, _ns13__ModifyAreaResponse &ns13__ModifyAreaResponse);
        /// Web service operation 'DeleteArea' (returns SOAP_OK or error code)
        virtual int DeleteArea(_ns13__DeleteArea *ns13__DeleteArea, _ns13__DeleteAreaResponse &ns13__DeleteAreaResponse)
        { return this->DeleteArea(NULL, NULL, ns13__DeleteArea, ns13__DeleteAreaResponse); }
        virtual int DeleteArea(const char *soap_endpoint, const char *soap_action, _ns13__DeleteArea *ns13__DeleteArea, _ns13__DeleteAreaResponse &ns13__DeleteAreaResponse);
        /// Web service operation 'GetAccessPointState' (returns SOAP_OK or error code)
        virtual int GetAccessPointState(_ns13__GetAccessPointState *ns13__GetAccessPointState, _ns13__GetAccessPointStateResponse &ns13__GetAccessPointStateResponse)
        { return this->GetAccessPointState(NULL, NULL, ns13__GetAccessPointState, ns13__GetAccessPointStateResponse); }
        virtual int GetAccessPointState(const char *soap_endpoint, const char *soap_action, _ns13__GetAccessPointState *ns13__GetAccessPointState, _ns13__GetAccessPointStateResponse &ns13__GetAccessPointStateResponse);
        /// Web service operation 'EnableAccessPoint' (returns SOAP_OK or error code)
        virtual int EnableAccessPoint(_ns13__EnableAccessPoint *ns13__EnableAccessPoint, _ns13__EnableAccessPointResponse &ns13__EnableAccessPointResponse)
        { return this->EnableAccessPoint(NULL, NULL, ns13__EnableAccessPoint, ns13__EnableAccessPointResponse); }
        virtual int EnableAccessPoint(const char *soap_endpoint, const char *soap_action, _ns13__EnableAccessPoint *ns13__EnableAccessPoint, _ns13__EnableAccessPointResponse &ns13__EnableAccessPointResponse);
        /// Web service operation 'DisableAccessPoint' (returns SOAP_OK or error code)
        virtual int DisableAccessPoint(_ns13__DisableAccessPoint *ns13__DisableAccessPoint, _ns13__DisableAccessPointResponse &ns13__DisableAccessPointResponse)
        { return this->DisableAccessPoint(NULL, NULL, ns13__DisableAccessPoint, ns13__DisableAccessPointResponse); }
        virtual int DisableAccessPoint(const char *soap_endpoint, const char *soap_action, _ns13__DisableAccessPoint *ns13__DisableAccessPoint, _ns13__DisableAccessPointResponse &ns13__DisableAccessPointResponse);
        /// Web service operation 'ExternalAuthorization' (returns SOAP_OK or error code)
        virtual int ExternalAuthorization(_ns13__ExternalAuthorization *ns13__ExternalAuthorization, _ns13__ExternalAuthorizationResponse &ns13__ExternalAuthorizationResponse)
        { return this->ExternalAuthorization(NULL, NULL, ns13__ExternalAuthorization, ns13__ExternalAuthorizationResponse); }
        virtual int ExternalAuthorization(const char *soap_endpoint, const char *soap_action, _ns13__ExternalAuthorization *ns13__ExternalAuthorization, _ns13__ExternalAuthorizationResponse &ns13__ExternalAuthorizationResponse);
    };
#endif
