/* soapAccessRulesBindingProxy.h
   Generated by gSOAP 2.8.45 for onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapAccessRulesBindingProxy_H
#define soapAccessRulesBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC AccessRulesBindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        bool soap_own; ///< flag indicating that this context is owned by this proxy when context is shared
        /// Endpoint URL of service 'AccessRulesBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in onvif.h, if any
        /// Construct a proxy with new managing context
        AccessRulesBindingProxy();
        /// Copy constructor
        AccessRulesBindingProxy(const AccessRulesBindingProxy& rhs);
        /// Construct proxy given a shared managing context
        AccessRulesBindingProxy(struct soap*);
        /// Constructor taking an endpoint URL
        AccessRulesBindingProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        AccessRulesBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        AccessRulesBindingProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        AccessRulesBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes non-shared managing context only (use destroy() to delete deserialized data)
        virtual ~AccessRulesBindingProxy();
        /// Initializer used by constructors
        virtual void AccessRulesBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual AccessRulesBindingProxy *copy() SOAP_PURE_VIRTUAL;
        /// Copy assignment
        AccessRulesBindingProxy& operator=(const AccessRulesBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Add SOAP Header to message
        virtual void soap_header(char *wsa__MessageID, struct wsa__Relationship *wsa__RelatesTo, struct wsa__EndpointReferenceType *wsa__From, struct wsa__EndpointReferenceType *wsa__ReplyTo, struct wsa__EndpointReferenceType *wsa__FaultTo, char *wsa__To, char *wsa__Action, struct wsdd__AppSequenceType *wsdd__AppSequence, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct _wsse__Security *wsse__Security);
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault string (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail as string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'GetServiceCapabilities' (returns SOAP_OK or error code)
        virtual int GetServiceCapabilities(_ns14__GetServiceCapabilities *ns14__GetServiceCapabilities, _ns14__GetServiceCapabilitiesResponse &ns14__GetServiceCapabilitiesResponse)
        { return this->GetServiceCapabilities(NULL, NULL, ns14__GetServiceCapabilities, ns14__GetServiceCapabilitiesResponse); }
        virtual int GetServiceCapabilities(const char *soap_endpoint, const char *soap_action, _ns14__GetServiceCapabilities *ns14__GetServiceCapabilities, _ns14__GetServiceCapabilitiesResponse &ns14__GetServiceCapabilitiesResponse);
        /// Web service operation 'GetAccessProfileInfo' (returns SOAP_OK or error code)
        virtual int GetAccessProfileInfo(_ns14__GetAccessProfileInfo *ns14__GetAccessProfileInfo, _ns14__GetAccessProfileInfoResponse &ns14__GetAccessProfileInfoResponse)
        { return this->GetAccessProfileInfo(NULL, NULL, ns14__GetAccessProfileInfo, ns14__GetAccessProfileInfoResponse); }
        virtual int GetAccessProfileInfo(const char *soap_endpoint, const char *soap_action, _ns14__GetAccessProfileInfo *ns14__GetAccessProfileInfo, _ns14__GetAccessProfileInfoResponse &ns14__GetAccessProfileInfoResponse);
        /// Web service operation 'GetAccessProfileInfoList' (returns SOAP_OK or error code)
        virtual int GetAccessProfileInfoList(_ns14__GetAccessProfileInfoList *ns14__GetAccessProfileInfoList, _ns14__GetAccessProfileInfoListResponse &ns14__GetAccessProfileInfoListResponse)
        { return this->GetAccessProfileInfoList(NULL, NULL, ns14__GetAccessProfileInfoList, ns14__GetAccessProfileInfoListResponse); }
        virtual int GetAccessProfileInfoList(const char *soap_endpoint, const char *soap_action, _ns14__GetAccessProfileInfoList *ns14__GetAccessProfileInfoList, _ns14__GetAccessProfileInfoListResponse &ns14__GetAccessProfileInfoListResponse);
        /// Web service operation 'GetAccessProfiles' (returns SOAP_OK or error code)
        virtual int GetAccessProfiles(_ns14__GetAccessProfiles *ns14__GetAccessProfiles, _ns14__GetAccessProfilesResponse &ns14__GetAccessProfilesResponse)
        { return this->GetAccessProfiles(NULL, NULL, ns14__GetAccessProfiles, ns14__GetAccessProfilesResponse); }
        virtual int GetAccessProfiles(const char *soap_endpoint, const char *soap_action, _ns14__GetAccessProfiles *ns14__GetAccessProfiles, _ns14__GetAccessProfilesResponse &ns14__GetAccessProfilesResponse);
        /// Web service operation 'GetAccessProfileList' (returns SOAP_OK or error code)
        virtual int GetAccessProfileList(_ns14__GetAccessProfileList *ns14__GetAccessProfileList, _ns14__GetAccessProfileListResponse &ns14__GetAccessProfileListResponse)
        { return this->GetAccessProfileList(NULL, NULL, ns14__GetAccessProfileList, ns14__GetAccessProfileListResponse); }
        virtual int GetAccessProfileList(const char *soap_endpoint, const char *soap_action, _ns14__GetAccessProfileList *ns14__GetAccessProfileList, _ns14__GetAccessProfileListResponse &ns14__GetAccessProfileListResponse);
        /// Web service operation 'CreateAccessProfile' (returns SOAP_OK or error code)
        virtual int CreateAccessProfile(_ns14__CreateAccessProfile *ns14__CreateAccessProfile, _ns14__CreateAccessProfileResponse &ns14__CreateAccessProfileResponse)
        { return this->CreateAccessProfile(NULL, NULL, ns14__CreateAccessProfile, ns14__CreateAccessProfileResponse); }
        virtual int CreateAccessProfile(const char *soap_endpoint, const char *soap_action, _ns14__CreateAccessProfile *ns14__CreateAccessProfile, _ns14__CreateAccessProfileResponse &ns14__CreateAccessProfileResponse);
        /// Web service operation 'ModifyAccessProfile' (returns SOAP_OK or error code)
        virtual int ModifyAccessProfile(_ns14__ModifyAccessProfile *ns14__ModifyAccessProfile, _ns14__ModifyAccessProfileResponse &ns14__ModifyAccessProfileResponse)
        { return this->ModifyAccessProfile(NULL, NULL, ns14__ModifyAccessProfile, ns14__ModifyAccessProfileResponse); }
        virtual int ModifyAccessProfile(const char *soap_endpoint, const char *soap_action, _ns14__ModifyAccessProfile *ns14__ModifyAccessProfile, _ns14__ModifyAccessProfileResponse &ns14__ModifyAccessProfileResponse);
        /// Web service operation 'SetAccessProfile' (returns SOAP_OK or error code)
        virtual int SetAccessProfile(_ns14__SetAccessProfile *ns14__SetAccessProfile, _ns14__SetAccessProfileResponse &ns14__SetAccessProfileResponse)
        { return this->SetAccessProfile(NULL, NULL, ns14__SetAccessProfile, ns14__SetAccessProfileResponse); }
        virtual int SetAccessProfile(const char *soap_endpoint, const char *soap_action, _ns14__SetAccessProfile *ns14__SetAccessProfile, _ns14__SetAccessProfileResponse &ns14__SetAccessProfileResponse);
        /// Web service operation 'DeleteAccessProfile' (returns SOAP_OK or error code)
        virtual int DeleteAccessProfile(_ns14__DeleteAccessProfile *ns14__DeleteAccessProfile, _ns14__DeleteAccessProfileResponse &ns14__DeleteAccessProfileResponse)
        { return this->DeleteAccessProfile(NULL, NULL, ns14__DeleteAccessProfile, ns14__DeleteAccessProfileResponse); }
        virtual int DeleteAccessProfile(const char *soap_endpoint, const char *soap_action, _ns14__DeleteAccessProfile *ns14__DeleteAccessProfile, _ns14__DeleteAccessProfileResponse &ns14__DeleteAccessProfileResponse);
    };
#endif
